### ISSUE TITLE
How can I visualize the hyperbolic embedding

### ISSUE THREAD

**Issue by amiltonwong** [HazyResearch/HypHC#1]
Hi, all,

After I run the scripts `examples/run_zoo.sh` and `example/run_glass.sh`, the trained model and log files are saved at ./embeddings as follows:

```
root@Lab-PC:/data/code14/HypHC/embeddings# tree .
.
├── glass
│   └── bc24ee553d3178d956bbb7a68d6058f5a48edb408c82a49e613a344d71602abf
│       ├── config.json
│       ├── model_0.pkl
│       └── train_0.log
└── zoo
    └── ca286289368cbe66abdfe32406cffed3ff5e6102252c0fc6502519713db04b83
        ├── config.json
        ├── model_0.pkl
        └── train_0.log
```

How can I visualize the hyperbolic embedding similar to demo file `HypHC.gif`?

Thanks~

**Comment by ines-chami** [comment]
I added a visualize.py script to visualize the embeddings and decoded trees. To use it: 
`python visualize.py --model_dir [PATH TO MODEL DIRECTORY]`

The script will save an embeddings.png file in the corresponding model directory.

**Comment by amiltonwong** [comment]
@ines-chami , thanks a lot. Got it. :)
